import { Row } from './type';

export const timeTableRows: Row[] = [
  {
    firstColumn: { slot: 'Slot 1', time: '7:30-9:50' },
    otherColumns: [
      {
        day: 'MON',
        class: 'SE1504-JS',
        subject: 'JFE301',
        room: 'BE301',
        lecturer: 'Sonnt69',
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
    ],
  },
  {
    firstColumn: { slot: 'Slot 2', time: '10:00-12:20' },
    otherColumns: [
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: 'TUE',
        class: 'SE1504-JS',
        subject: 'JFE301',
        room: 'BE301',
        lecturer: 'Sonnt69',
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: 'THU',
        class: 'SE1504-JS',
        subject: 'JFE301',
        room: 'BE301',
        lecturer: 'Sonnt69',
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
    ],
  },
  {
    firstColumn: { slot: 'Slot 3', time: '12:50-15:10' },
    otherColumns: [
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: 'THU',
        class: 'SE1504-JS',
        subject: 'JFE301',
        room: 'BE301',
        lecturer: 'Sonnt69',
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
    ],
  },
  {
    firstColumn: { slot: 'Slot 4', time: '15:20-17:40' },
    otherColumns: [
      {
        day: 'MON',
        class: 'SE1504-JS',
        subject: 'JFE301',
        room: 'BE301',
        lecturer: 'Sonnt69',
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: 'FRI',
        class: 'SE1504-JS',
        subject: 'JFE301',
        room: 'BE301',
        lecturer: 'Sonnt69',
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
      {
        day: null,
        class: null,
        subject: null,
        room: null,
        lecturer: null,
      },
    ],
  },
];
