import {
  LecturerSlotsPreferenceLevel,
  LecturerSubjectsPreferenceLevel,
} from './types';

export const lecturerSubjectPreferenceLevel: LecturerSubjectsPreferenceLevel[] =
  [
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
  ];

export const lecturerSlotPreferenceLevel: LecturerSlotsPreferenceLevel[] = [
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
];
