import {
  LecturerSlotsPreferenceLevel,
  LecturerSubjectsPreferenceLevel,
  SlotPreferenceLevelItems,
  SubjectPreferenceLevelItems,
} from './types';

export const subjectPreferenceLevelItems: SubjectPreferenceLevelItems[] = [
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
];

export const slotPreferenceLevelItems: SlotPreferenceLevelItems[] = [
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
];

export const lecturerSubjectPreferenceLevel: LecturerSubjectsPreferenceLevel[] =
  [
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
    {
      id: 1,
      lecturer: 'chiendc',
      subjects: [
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
        { id: 1, name: 'ABC', preferenceLevel: 1 },
      ],
    },
  ];

export const lecturerSlotPreferenceLevel: LecturerSlotsPreferenceLevel[] = [
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
  {
    id: 1,
    lecturer: 'chiendc',
    slots: [
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
      { id: 1, name: 'ABC', preferenceLevel: 1 },
    ],
  },
];
