import {
  AreaSlotWeightSelectItem,
  SlotCompatibilityData,
  SlotConflictData,
  SlotConflictSelectItem,
  SlotWeightData,
} from './type';

export const slotConflictItem: SlotConflictSelectItem[] = [
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
];

export const areaSlotWeightItem: AreaSlotWeightSelectItem[] = [
  { value: 0, label: '0' },
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
  { value: 4, label: '4' },
  { value: 5, label: '5' },
];

export const areaSlotWeightData: SlotWeightData[] = [
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
      { id: 1, name: 'A24', slotWeight: 0 },
    ],
  },
];
export const slotConflictData: SlotConflictData[] = [
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
];
export const slotCompatibilityData: SlotCompatibilityData[] = [
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
];
