import { SlotCompatibilityData, SlotConflictData } from './type';

export const slotConflictData: SlotConflictData[] = [
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
];
export const slotCompatibilityData: SlotCompatibilityData[] = [
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
  {
    id: 1,
    slot: 'A24',
    slots: [
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
      { id: 1, name: 'A24', conflictLevel: 0 },
    ],
  },
];
